/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Complaint = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'resolutionNote' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'category' : IDL.Text,
  'priority' : IDL.Opt(IDL.Text),
  'flatNumber' : IDL.Nat,
});
export const MaintenanceRecord = IDL.Record({
  'paymentTimestamp' : IDL.Opt(Time),
  'month' : IDL.Text,
  'year' : IDL.Nat,
  'isPaid' : IDL.Bool,
  'upiRef' : IDL.Opt(IDL.Text),
  'flatNumber' : IDL.Nat,
});
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'expiryDate' : IDL.Opt(Time),
  'message' : IDL.Text,
});
export const VisitorRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'visitorName' : IDL.Text,
  'purpose' : IDL.Text,
  'flatNumber' : IDL.Nat,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Text,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'flatNumber' : IDL.Opt(IDL.Nat),
});
export const Expenditure = IDL.Record({
  'month' : IDL.Text,
  'year' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const FlatPaymentStatus = IDL.Record({
  'paymentTimestamp' : IDL.Opt(Time),
  'isPaid' : IDL.Bool,
  'upiRef' : IDL.Opt(IDL.Text),
  'flatNumber' : IDL.Nat,
});
export const SecretarySettings = IDL.Record({
  'guardMobileNumber' : IDL.Text,
  'upiId' : IDL.Text,
  'maintenanceAmount' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'checkAndNotifyOverdueMaintenance' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [],
      ['oneway'],
    ),
  'createNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(Time)], [IDL.Nat], []),
  'createVisitorRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getAllMaintenanceRecords' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(MaintenanceRecord)],
      ['query'],
    ),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getAllVisitorRequests' : IDL.Func([], [IDL.Vec(VisitorRequest)], ['query']),
  'getCallerNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaintsByFlat' : IDL.Func([IDL.Nat], [IDL.Vec(Complaint)], ['query']),
  'getExpenditures' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(Expenditure)],
      ['query'],
    ),
  'getFlatMobileNumbers' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getMaintenanceAmount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMaintenanceRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Opt(MaintenanceRecord)],
      ['query'],
    ),
  'getMaintenanceStatusForAllFlats' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(FlatPaymentStatus)],
      ['query'],
    ),
  'getOverdueFlats' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getSecretarySettings' : IDL.Func([], [SecretarySettings], ['query']),
  'getUpiId' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorRequestsByFlat' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(VisitorRequest)],
      ['query'],
    ),
  'getWhatsappNumber' : IDL.Func([], [IDL.Text], ['query']),
  'initializePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'lodgeComplaint' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'markAllNotificationsAsRead' : IDL.Func([], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'notifyOverdueFlats' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'promoteToSecretary' : IDL.Func([IDL.Principal], [], []),
  'recordExpenditure' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'recordPayment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, Time],
      [],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setUpiId' : IDL.Func([IDL.Text], [], []),
  'setWhatsappNumber' : IDL.Func([IDL.Text], [], []),
  'updateComplaintStatus' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateFlatMobileNumbers' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  'updateSecretarySettings' : IDL.Func([SecretarySettings], [], []),
  'updateVisitorRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Complaint = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'resolutionNote' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'category' : IDL.Text,
    'priority' : IDL.Opt(IDL.Text),
    'flatNumber' : IDL.Nat,
  });
  const MaintenanceRecord = IDL.Record({
    'paymentTimestamp' : IDL.Opt(Time),
    'month' : IDL.Text,
    'year' : IDL.Nat,
    'isPaid' : IDL.Bool,
    'upiRef' : IDL.Opt(IDL.Text),
    'flatNumber' : IDL.Nat,
  });
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'expiryDate' : IDL.Opt(Time),
    'message' : IDL.Text,
  });
  const VisitorRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'visitorName' : IDL.Text,
    'purpose' : IDL.Text,
    'flatNumber' : IDL.Nat,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Text,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'flatNumber' : IDL.Opt(IDL.Nat),
  });
  const Expenditure = IDL.Record({
    'month' : IDL.Text,
    'year' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const FlatPaymentStatus = IDL.Record({
    'paymentTimestamp' : IDL.Opt(Time),
    'isPaid' : IDL.Bool,
    'upiRef' : IDL.Opt(IDL.Text),
    'flatNumber' : IDL.Nat,
  });
  const SecretarySettings = IDL.Record({
    'guardMobileNumber' : IDL.Text,
    'upiId' : IDL.Text,
    'maintenanceAmount' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'checkAndNotifyOverdueMaintenance' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [],
        ['oneway'],
      ),
    'createNotice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(Time)],
        [IDL.Nat],
        [],
      ),
    'createVisitorRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getAllMaintenanceRecords' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(MaintenanceRecord)],
        ['query'],
      ),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getAllVisitorRequests' : IDL.Func(
        [],
        [IDL.Vec(VisitorRequest)],
        ['query'],
      ),
    'getCallerNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaintsByFlat' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getExpenditures' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(Expenditure)],
        ['query'],
      ),
    'getFlatMobileNumbers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getMaintenanceAmount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMaintenanceRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Opt(MaintenanceRecord)],
        ['query'],
      ),
    'getMaintenanceStatusForAllFlats' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(FlatPaymentStatus)],
        ['query'],
      ),
    'getOverdueFlats' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getSecretarySettings' : IDL.Func([], [SecretarySettings], ['query']),
    'getUpiId' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorRequestsByFlat' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(VisitorRequest)],
        ['query'],
      ),
    'getWhatsappNumber' : IDL.Func([], [IDL.Text], ['query']),
    'initializePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'lodgeComplaint' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'markAllNotificationsAsRead' : IDL.Func([], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'notifyOverdueFlats' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'promoteToSecretary' : IDL.Func([IDL.Principal], [], []),
    'recordExpenditure' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'recordPayment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, Time],
        [],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setUpiId' : IDL.Func([IDL.Text], [], []),
    'setWhatsappNumber' : IDL.Func([IDL.Text], [], []),
    'updateComplaintStatus' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateFlatMobileNumbers' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
    'updateSecretarySettings' : IDL.Func([SecretarySettings], [], []),
    'updateVisitorRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };