/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Complaint {
  'id' : bigint,
  'status' : string,
  'resolutionNote' : [] | [string],
  'description' : string,
  'category' : string,
  'priority' : [] | [string],
  'flatNumber' : bigint,
}
export interface Expenditure {
  'month' : string,
  'year' : bigint,
  'totalAmount' : bigint,
  'notes' : [] | [string],
  'items' : Array<[string, bigint]>,
}
export interface FlatPaymentStatus {
  'paymentTimestamp' : [] | [Time],
  'isPaid' : boolean,
  'upiRef' : [] | [string],
  'flatNumber' : bigint,
}
export interface MaintenanceRecord {
  'paymentTimestamp' : [] | [Time],
  'month' : string,
  'year' : bigint,
  'isPaid' : boolean,
  'upiRef' : [] | [string],
  'flatNumber' : bigint,
}
export interface Notice {
  'id' : bigint,
  'title' : string,
  'expiryDate' : [] | [Time],
  'message' : string,
}
export interface Notification {
  'id' : bigint,
  'recipient' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export interface SecretarySettings {
  'guardMobileNumber' : string,
  'upiId' : string,
  'maintenanceAmount' : bigint,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'userType' : string,
  'userId' : string,
  'name' : string,
  'flatNumber' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitorRequest {
  'id' : bigint,
  'status' : string,
  'mobileNumber' : string,
  'visitorName' : string,
  'purpose' : string,
  'flatNumber' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changePassword' : ActorMethod<[string, string, string], undefined>,
  'checkAndNotifyOverdueMaintenance' : ActorMethod<
    [bigint, string, bigint],
    undefined
  >,
  'createNotice' : ActorMethod<[string, string, [] | [Time]], bigint>,
  'createVisitorRequest' : ActorMethod<
    [string, string, bigint, string],
    bigint
  >,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getAllMaintenanceRecords' : ActorMethod<
    [string, bigint],
    Array<MaintenanceRecord>
  >,
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  'getAllVisitorRequests' : ActorMethod<[], Array<VisitorRequest>>,
  'getCallerNotifications' : ActorMethod<[], Array<Notification>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaintsByFlat' : ActorMethod<[bigint], Array<Complaint>>,
  'getExpenditures' : ActorMethod<[string, bigint], [] | [Expenditure]>,
  'getFlatMobileNumbers' : ActorMethod<[bigint], Array<string>>,
  'getMaintenanceAmount' : ActorMethod<[], bigint>,
  'getMaintenanceRecord' : ActorMethod<
    [bigint, string, bigint],
    [] | [MaintenanceRecord]
  >,
  'getMaintenanceStatusForAllFlats' : ActorMethod<
    [string, bigint],
    Array<FlatPaymentStatus>
  >,
  'getOverdueFlats' : ActorMethod<[string, bigint], Array<bigint>>,
  'getSecretarySettings' : ActorMethod<[], SecretarySettings>,
  'getUpiId' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorRequestsByFlat' : ActorMethod<[bigint], Array<VisitorRequest>>,
  'getWhatsappNumber' : ActorMethod<[], string>,
  'initializePassword' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'lodgeComplaint' : ActorMethod<
    [bigint, string, string, [] | [string]],
    bigint
  >,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'notifyOverdueFlats' : ActorMethod<[string, bigint], undefined>,
  'promoteToSecretary' : ActorMethod<[Principal], undefined>,
  'recordExpenditure' : ActorMethod<
    [string, bigint, Array<[string, bigint]>, bigint, [] | [string]],
    undefined
  >,
  'recordPayment' : ActorMethod<
    [bigint, string, bigint, string, Time],
    undefined
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setUpiId' : ActorMethod<[string], undefined>,
  'setWhatsappNumber' : ActorMethod<[string], undefined>,
  'updateComplaintStatus' : ActorMethod<
    [bigint, string, [] | [string]],
    undefined
  >,
  'updateFlatMobileNumbers' : ActorMethod<[bigint, Array<string>], undefined>,
  'updateSecretarySettings' : ActorMethod<[SecretarySettings], undefined>,
  'updateVisitorRequestStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];